on: push
name: CI
jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pxgamer/composer-action@v2
      - uses: pxgamer/phpunit-action@490eaead812c179f5d488e0f662d5000aa07115c
